name: Publish Docker image

# Doesn't starts after release-on-tag.yaml Unsure why.
#on:
#  release:
#    types: [created]
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set Version Variable for ldflags
        run: echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          build-args: |
            VERSION=${{ env.VERSION }}
          push: true
          tags: |
            galan/repow:${{ env.VERSION }}
            galan/repow:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
